name: Setup build environment
description: Installs Android SDK, NDK (with caching) and zip

runs:
  using: composite
  steps:
    - name: Setup Android SDK
      uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699  # v4

    - name: Install build dependencies
      shell: bash
      run: sudo apt-get install -y zip

    - name: Cache Android home
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4
      id: cache-android-home
      with:
        path: ${{ env.ANDROID_HOME }}
        key: android-home-${{ hashFiles('Makefile') }}

    - name: Install SDK components
      if: steps.cache-android-home.outputs.cache-hit != 'true'
      shell: bash
      run: make sdk
